version: '3.8'

services:
  # FastAPI Application
  api:
    build:
      context: https://github.com/indrapurnayasa/exportco.git#main
      dockerfile: Dockerfile
    container_name: exportco_api
    ports:
      - "${PORT:-8000}:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_DB=${POSTGRES_DB:-hackathondb}
      - POSTGRES_USER=${POSTGRES_USER:-maverick}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-1946@Maverick}
      - POSTGRES_HOST=${POSTGRES_HOST:-hackathon-bi}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - ALGORITHM=${ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-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}
      - OPENAI_EMBEDDING_MODEL=${OPENAI_EMBEDDING_MODEL:-text-embedding-ada-002}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PROJECT_NAME=${PROJECT_NAME:-ExportCo API}
      - VERSION=${VERSION:-1.0.0}
      - DEBUG=${DEBUG:-false}
    env_file:
      - .env
    restart: always
    networks:
      - default
    volumes:
      - ./logs:/app/logs
      - ./backups:/app/backups
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
