version: '3.8'
services:
  api:
    image: ${DOCKER_USERNAME}/exportco:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
