version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Database settings
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/exportco
      - DB_POOL_SIZE=20
      - DB_MAX_OVERFLOW=30
      - DB_POOL_TIMEOUT=30
      - DB_POOL_RECYCLE=3600

      # Security settings
      - SECRET_KEY=your-secret-key-here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

      # Rate limiting settings
      - RATE_LIMIT_REQUESTS=100
      - RATE_LIMIT_WINDOW=1

      # Cache settings
      - CACHE_TTL=300
      - CACHE_MAX_SIZE=1000

      # Query limits
      - MAX_QUERY_LIMIT=10000
      - QUERY_TIMEOUT=30

      # Logging
      - LOG_LEVEL=INFO
    depends_on:
      - db
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=exportco
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
