name: exportco
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - fastapi==0.104.1
      - uvicorn[standard]==0.24.0
      - sqlalchemy==2.0.23
      - pydantic[email]==2.4.2
      - python-jose[cryptography]==3.3.0
      - passlib[bcrypt]==1.7.4
      - python-multipart==0.0.6
      - alembic==1.12.1
      - pytest==7.4.3
      - pytest-asyncio==0.21.1
      - httpx==0.25.2
      - python-dotenv==1.0.0
      - psycopg2-binary==2.9.9
      - asyncpg==0.29.0
      - greenlet==3.0.1
      - openai==1.3.7
      - pgvector==0.2.3
